apiVersion: apps/v1
kind: Deployment
metadata:
  name: udafrontend
  labels:
    app: udafrontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udafrontend
  template:
    metadata:
      labels:
        app: udafrontend
    spec:
      containers:
      - name: udagram-frontend
        image: swapnaudacity/udagram-frontend
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3
